### ISSUE TITLE
Task 2a: Address an issue in a collaborative project

### ISSUE THREAD

**Issue by koudyk** [koudyk/intro_git_github#12]
**GOAL:** practice the workflow of contributing to an open project, in particular, addressing an issue posted by someone else
**TASK:** add a file called `<your_username>.csv` in the folder `ssc_workshop`, containing a comma-separated list of your favorite desserts. 
**NOTE**: replace things inside <> with your own info

0. Comment on this issue saying that you can work on it

1. Fork this repository ("Fork" button on top right of this page)

2. Clone your fork to your machine 
`git clone https://github.com/<your_username>/intro_git_github.git`
If that doesn't work, try
`git clone git@github.com:<github username>/<github repo name>.git `

3. Change into the git reop
`cd intro_git_github`

3. Your fork is now your 'origin' remote. Now add this (my) repo as the 'upstream' remote so you can pull other peoples' changes in the future
`git remote add upstream https://github.com/koudyk/intro_git_github.git`

4. Start a new branch 
`git checkout -b <yourbranch>`

5. make a csv file in the folder **ssc_workshop** called `<your_username>.csv` 
`mkdir ssc_workshop`
`cd ssc_workshop`
`touch <your_username>.csv`

6. list your favorite deserts, **with a SPELLING MISTAKE**, each separated by a comma. 
To open it: <text editor> <filename> or find the file through your file navigator and open it. 
E.g., you could write in it: 
> speculaas, ize cream, chocolate

7. save the file

8. (optional) Try inspecting what git is/isn't tracking with `git status` and/or `git status`

9. stage the change 
`git add <filename>` 

10. commit the change 
`git commit -m "<short, informative commit message>"`

11. push the change 
`git push origin <yourbranch>`

12. Go to your forked version of this repository on GitHub (`https://github.com/<your_username>/intro_git_github`)

13. Open a pull request

**Comment by koudyk** [comment]
I'm going to work on this

**Comment by AJCanty** [comment]
I will (try to) work on this too!

**Comment by lelovblom** [comment]
Also working on it
